---
- hosts: all
  become: yes
  tasks:
    - name: Check if swap is already active
      command: swapon --show
      register: swap_status
      changed_when: false

    - name: Create swap file
      when: swap_status.stdout == ""
      command: fallocate -l 2G /swapfile
      args:
        creates: /swapfile

    - name: Set permissions for swap file
      when: swap_status.stdout == ""
      file:
        path: /swapfile
        mode: '0600'

    - name: Make swap
      when: swap_status.stdout == ""
      command: mkswap /swapfile
      
    - name: Turn on swap
      when: swap_status.stdout == ""
      command: swapon /swapfile

    - name: Add swap to fstab for persistence
      when: swap_status.stdout == ""
      lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
