apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
    environment: $DEPLOY_ENV
spec:
  replicas: $REPLICAS
  minReadySeconds: $MIN_READY_SECONDS
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
        environment: $DEPLOY_ENV
        version: "$env.IMAGE_NAME"
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      imagePullSecrets:
        - name: my-registry-key
      containers:
      - name: $APP_NAME
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
        image: awaisakram11199/devopsimages:$env.IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "$DEPLOY_ENV"
        - name: APP_NAME
          value: "$APP_NAME"
        readinessProbe:
            periodSeconds: 10
            initialDelaySeconds: 20
            httpGet:
              path: /actuator/health/readiness
              port: 8090
        livenessProbe:
            periodSeconds: 10
            initialDelaySeconds: 30
            httpGet:
              path: /actuator/health/liveness
              port: 8090
        resources:
            requests:
              cpu: $CPU_REQUEST
              memory: $MEMORY_REQUEST
            limits:
              cpu: $CPU_LIMIT
              memory: $MEMORY_LIMIT

