apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-$SLOT
  labels:
    app: $APP_NAME
    slot: $SLOT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
      slot: $SLOT
  template:
    metadata:
      labels:
        app: $APP_NAME
        slot: $SLOT
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      imagePullSecrets:
        - name: my-registry-key
      containers:
      - name: $APP_NAME
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
        # Add a volume mount for the logs directory
        volumeMounts:
        - name: logs-volume
          mountPath: /usr/app/logs
        # Add a volume mount for the temp directory
        - name: tmp-volume
          mountPath: /tmp
        image: awaisakram11199/devopsimages:$IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          name: http
        readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
        livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
        resources:
            requests:
              cpu: 400m
              memory: 256Mi
            limits:
              cpu: 600m
              memory: 512Mi
      # Define the volume that will be mounted
      volumes:
      - name: logs-volume
        emptyDir: {}
      # Define the volume for the temp directory
      - name: tmp-volume
        emptyDir: {}
