apiVersion: v1
kind: PersistentVolume
metadata:
  name: $APP_NAME  
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Delete
  storageClassName: $APP_NAME  # Link to the StorageClass you created
  csi:
    driver: ebs.csi.aws.com  # AWS EBS driver
    volumeHandle: vol-059dce2ee96ac126a  # EBS volume ID (for static provisioning)
