apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
  selector:
    app: $APP_NAME
    # This selector will be patched by Jenkins to 'blue' or 'green'
    slot: $ACTIVE_SLOT
